name: Static analysis of Node

on:
  push:
    paths:
    - 'Project1/device/**'
      
defaults:
  run:
    working-directory: Project1
        
jobs:
  static-Code-analysis:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run:  sudo apt-get install cppcheck 
              
    - uses: actions/checkout@v2
    - name: Static analysis using cppcheck
      run:  |
            echo "Executing script files" 
            chmod 777 sca.sh
            ./sca.sh
                      
    - uses: actions/upload-artifact@v2
      with:
         name: Project1report
         path: report/sca.xml
