name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Static Code analysis:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Static analysis using cppcheck
      run:  cppcheck --enable=all  static.c
