name: C/C++ CI

on:
  push:
    paths-ignore:
    - 'Project2/**'


jobs:
  static-Code-analysis:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
           sudo apt-get install cppcheck 
           
    - uses: actions/checkout@v2
    - name: Static analysis using cppcheck
      run:  cppcheck --enable=all  Project1
