name: C/C++ CI

on:
  push:
    paths:
    - 'Project1/**'
    - 'Project2/**'


jobs:
  static-Code-analysis:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
           sudo apt-get install cppcheck 
    - run: mkdir -p temp

    - run: echo hello > temp/world.txt

    - uses: actions/upload-artifact@v2
      with:
         name: my-artifact
         path: temp/world.txt   
             
    - uses: actions/checkout@v2
    - name: Static analysis using cppcheck
      run:  cppcheck --enable=all  Project1
